package com.cmv.petGenesis.command;

public enum HistoryCommands {
	CMD_BTN_CREATE_HISTORY, CMD_BTN_UPDATE_HISTORY, CMD_BTN_STATE_HISTORY, CMD_BTN_FIND_HISTORY,
	CMD_WD_COMMENTS_CLEAR_COM, CMD_WD_MEDICINE_CLEAR_VAC, CMD_WD_MEDICINE_CLEAR_ANTI, CMD_WD_EXAM_CLEAR_FIELDS,
	CMD_WD_PET_REGISTER_HIS, CMD_BTN_NEW_CLIENT, CMD_BTN_SEARCH_CLIENT,CMD_BTN_KEEP_HISTORY

}
