package com.cmv.petGenesis.command;

public enum UserCommands {
	OK_SIGN_IN, CMD_CREATE_USER, CMD_UPDATE_USER, CMD_INACTIV_USER, CMD_FIND_USER, CMD_SEARCH_USER, CMD_LOAD_DATA,
	CMD_WD_UPDATE_CHANGE_DATA, CMD_WD_UPDATE_RETURN, CMD_WD_UPDATE_SEARCH, CMD_WD_INACTIV_CHANGE_TABLE,
	CMD_WD_INACTIV_EXECUTE
}